package servlet;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Event <br>
 * @version generated on Thu Jun 21 13:30:55 JST 2018 by nurulfirdaus
 */

public interface Event extends WrappedIndividual {

    /* ***************************************************
     * Property http://purl.org/NET/c4dm/event.owl#hasFactor
     */
     
    /**
     * Gets all property values for the hasFactor property.<p>
     * 
     * @returns a collection of values for the hasFactor property.
     */
    Collection<? extends WrappedIndividual> getHasFactor();

    /**
     * Checks if the class has a hasFactor property value.<p>
     * 
     * @return true if there is a hasFactor property value.
     */
    boolean hasHasFactor();

    /**
     * Adds a hasFactor property value.<p>
     * 
     * @param newHasFactor the hasFactor property value to be added
     */
    void addHasFactor(WrappedIndividual newHasFactor);

    /**
     * Removes a hasFactor property value.<p>
     * 
     * @param oldHasFactor the hasFactor property value to be removed.
     */
    void removeHasFactor(WrappedIndividual oldHasFactor);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
