package servlet;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Jun 21 13:30:54 JST 2018 by nurulfirdaus
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://purl.org/NET/c4dm/event.owl#Event
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_EVENT = factory.getOWLClass(IRI.create("http://purl.org/NET/c4dm/event.owl#Event"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#AgricultureLand
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGRICULTURELAND.<p>
     * 
     */
    public static final OWLClass CLASS_AGRICULTURELAND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#AgricultureLand"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AREA.<p>
     * 
     */
    public static final OWLClass CLASS_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_exclusively_low-rise_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_II_EXCLUSIVELY_LOW_RISE_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_II_EXCLUSIVELY_LOW_RISE_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_exclusively_low-rise_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_mid_high-rise_oriented_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_II_MID_HIGH_RISE_ORIENTED_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_II_MID_HIGH_RISE_ORIENTED_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_mid_high-rise_oriented_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_II_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_II_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_II_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_exclusively_low-rise_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_I_EXCLUSIVELY_LOW_RISE_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_I_EXCLUSIVELY_LOW_RISE_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_exclusively_low-rise_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_mid_high-rise_oriented_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_I_MID_HIGH_RISE_ORIENTED_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_I_MID_HIGH_RISE_ORIENTED_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_mid_high-rise_oriented_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_residential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORY_I_RESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORY_I_RESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Category_I_residential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Commercial_Area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMERCIAL_AREA.<p>
     * 
     */
    public static final OWLClass CLASS_COMMERCIAL_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Commercial_Area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Commercial_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMERCIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_COMMERCIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Commercial_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Community_Center
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMUNITY_CENTER.<p>
     * 
     */
    public static final OWLClass CLASS_COMMUNITY_CENTER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Community_Center"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#DayCare
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DAYCARE.<p>
     * 
     */
    public static final OWLClass CLASS_DAYCARE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#DayCare"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Exclusively_industrial_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXCLUSIVELY_INDUSTRIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_EXCLUSIVELY_INDUSTRIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Exclusively_industrial_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#ForestLand
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORESTLAND.<p>
     * 
     */
    public static final OWLClass CLASS_FORESTLAND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#ForestLand"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Hospital
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOSPITAL.<p>
     * 
     */
    public static final OWLClass CLASS_HOSPITAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Hospital"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Hotel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTEL.<p>
     * 
     */
    public static final OWLClass CLASS_HOTEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Hotel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Industrial_Area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDUSTRIAL_AREA.<p>
     * 
     */
    public static final OWLClass CLASS_INDUSTRIAL_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Industrial_Area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Industrial_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDUSTRIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_INDUSTRIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Industrial_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Kindergarten
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class KINDERGARTEN.<p>
     * 
     */
    public static final OWLClass CLASS_KINDERGARTEN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Kindergarten"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandAndBuilding
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANDANDBUILDING.<p>
     * 
     */
    public static final OWLClass CLASS_LANDANDBUILDING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandAndBuilding"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandOnly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANDONLY.<p>
     * 
     */
    public static final OWLClass CLASS_LANDONLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandOnly"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandUseZones
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANDUSEZONES.<p>
     * 
     */
    public static final OWLClass CLASS_LANDUSEZONES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#LandUseZones"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Library
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIBRARY.<p>
     * 
     */
    public static final OWLClass CLASS_LIBRARY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Library"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Location
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATION.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Location"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Neighborhood_commercial_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEIGHBORHOOD_COMMERCIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_NEIGHBORHOOD_COMMERCIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Neighborhood_commercial_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Office
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OFFICE.<p>
     * 
     */
    public static final OWLClass CLASS_OFFICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Office"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#POIs
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POIS.<p>
     * 
     */
    public static final OWLClass CLASS_POIS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#POIs"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Potential_Residential_Area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POTENTIAL_RESIDENTIAL_AREA.<p>
     * 
     */
    public static final OWLClass CLASS_POTENTIAL_RESIDENTIAL_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Potential_Residential_Area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Pre-owned_Condominiums
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRE_OWNED_CONDOMINIUMS.<p>
     * 
     */
    public static final OWLClass CLASS_PRE_OWNED_CONDOMINIUMS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Pre-owned_Condominiums"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Prefecture
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PREFECTURE.<p>
     * 
     */
    public static final OWLClass CLASS_PREFECTURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Prefecture"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Quasiindustrial_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUASIINDUSTRIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_QUASIINDUSTRIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Quasiindustrial_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Quasiresidential_zone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUASIRESIDENTIAL_ZONE.<p>
     * 
     */
    public static final OWLClass CLASS_QUASIRESIDENTIAL_ZONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Quasiresidential_zone"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#RealEstate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REALESTATE.<p>
     * 
     */
    public static final OWLClass CLASS_REALESTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#RealEstate"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#ResidentialLand
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESIDENTIALLAND.<p>
     * 
     */
    public static final OWLClass CLASS_RESIDENTIALLAND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#ResidentialLand"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Residential_Area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESIDENTIAL_AREA.<p>
     * 
     */
    public static final OWLClass CLASS_RESIDENTIAL_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Residential_Area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Restaurant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTAURANT.<p>
     * 
     */
    public static final OWLClass CLASS_RESTAURANT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Restaurant"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#School
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHOOL.<p>
     * 
     */
    public static final OWLClass CLASS_SCHOOL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#School"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Shopping_Center
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SHOPPING_CENTER.<p>
     * 
     */
    public static final OWLClass CLASS_SHOPPING_CENTER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Shopping_Center"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Station
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATION.<p>
     * 
     */
    public static final OWLClass CLASS_STATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Station"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Transaction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSACTION.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSACTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#Transaction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#University
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UNIVERSITY.<p>
     * 
     */
    public static final OWLClass CLASS_UNIVERSITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#University"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#regionOfRealEstate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REGIONOFREALESTATE.<p>
     * 
     */
    public static final OWLClass CLASS_REGIONOFREALESTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#regionOfRealEstate"));

    /* ***************************************************
     * Class http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#typeOfRealEstate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TYPEOFREALESTATE.<p>
     * 
     */
    public static final OWLClass CLASS_TYPEOFREALESTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#typeOfRealEstate"));

    /* ***************************************************
     * Class http://www.w3.org/2006/time#DistanceToStation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTANCETOSTATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISTANCETOSTATION = factory.getOWLClass(IRI.create("http://www.w3.org/2006/time#DistanceToStation"));

    /* ***************************************************
     * Class http://www.w3.org/2006/time#TemporalPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORAL_POSITION.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORAL_POSITION = factory.getOWLClass(IRI.create("http://www.w3.org/2006/time#TemporalPosition"));

    /* ***************************************************
     * Class http://www.w3.org/2006/time#TransactionPeriod
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSACTIONPERIOD.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSACTIONPERIOD = factory.getOWLClass(IRI.create("http://www.w3.org/2006/time#TransactionPeriod"));

    /* ***************************************************
     * Class http://www.w3.org/2006/time#TransactionPrice
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSACTIONPRICE.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSACTIONPRICE = factory.getOWLClass(IRI.create("http://www.w3.org/2006/time#TransactionPrice"));

    /* ***************************************************
     * Object Property http://dbpedia.org/ontology/agglomerationPopulation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DBO:AGGLOMERATIONPOPULATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DBO:AGGLOMERATIONPOPULATION = factory.getOWLObjectProperty(IRI.create("http://dbpedia.org/ontology/agglomerationPopulation"));

    /* ***************************************************
     * Object Property http://dbpedia.org/ontology/population
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DBO:POPULATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DBO:POPULATION = factory.getOWLObjectProperty(IRI.create("http://dbpedia.org/ontology/population"));

    /* ***************************************************
     * Object Property http://dbpedia.org/ontology/previousPopulation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DBO:PREVIOUSPOPULATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DBO:PREVIOUSPOPULATION = factory.getOWLObjectProperty(IRI.create("http://dbpedia.org/ontology/previousPopulation"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#agent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AGENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AGENT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#agent"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#agent_in
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AGENT_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AGENT_IN = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#agent_in"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#factor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FACTOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FACTOR = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#factor"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#factor_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FACTOR_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FACTOR_OF = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#factor_of"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#hasAgent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASAGENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASAGENT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#hasAgent"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#hasFactor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFACTOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFACTOR = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#hasFactor"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#hasProduct
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPRODUCT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPRODUCT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#hasProduct"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#hasSubEvent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSUBEVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSUBEVENT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#hasSubEvent"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#isAgentIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AGENT_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AGENT_IN = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#isAgentIn"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#isFactorOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FACTOR_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FACTOR_OF = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#isFactorOf"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#place
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLACE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLACE = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#place"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#producedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCED_IN = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#producedIn"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#produced_in
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCED_IN = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#produced_in"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#product
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#product"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#sub_event
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUB_EVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUB_EVENT = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#sub_event"));

    /* ***************************************************
     * Object Property http://purl.org/NET/c4dm/event.owl#time
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TIME = factory.getOWLObjectProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#time"));

    /* ***************************************************
     * Object Property http://purl.org/dc/terms/type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DCTERMS:TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DCTERMS:TYPE = factory.getOWLObjectProperty(IRI.create("http://purl.org/dc/terms/type"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#Code
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CODE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CODE = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#Code"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#childrenFeatures
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CHILDREN_FEATURES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CHILDREN_FEATURES = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#childrenFeatures"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#featureClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FEATURE_CLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FEATURE_CLASS = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#featureClass"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#featureCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FEATURE_CODE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FEATURE_CODE = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#featureCode"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#locatedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOCATED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOCATED_IN = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#locatedIn"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#locationMap
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAP = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#locationMap"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#nearby
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEARBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEARBY = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#nearby"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#nearbyFeatures
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEARBY_FEATURES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEARBY_FEATURES = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#nearbyFeatures"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#neighbour
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEIGHBOUR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEIGHBOUR = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#neighbour"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#neighbouringFeatures
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEIGHBOURING_FEATURES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEIGHBOURING_FEATURES = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#neighbouringFeatures"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentADM1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LEVEL_1_ADMINISTRATIVE_PARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LEVEL_1_ADMINISTRATIVE_PARENT = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentADM1"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentADM2
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LEVEL_2_ADMINISTRATIVE_PARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LEVEL_2_ADMINISTRATIVE_PARENT = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentADM2"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentADM3
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LEVEL_3_ADMINISTRATIVE_PARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LEVEL_3_ADMINISTRATIVE_PARENT = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentADM3"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentADM4
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LEVEL_4_ADMINISTRATIVE_PARENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LEVEL_4_ADMINISTRATIVE_PARENT = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentADM4"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentCountry
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARENT_COUNTRY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARENT_COUNTRY = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentCountry"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#parentFeature
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARENT_FEATURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARENT_FEATURE = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#parentFeature"));

    /* ***************************************************
     * Object Property http://www.geonames.org/ontology#wikipediaArticle
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WIKIPEDIA_ARTICLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WIKIPEDIA_ARTICLE = factory.getOWLObjectProperty(IRI.create("http://www.geonames.org/ontology#wikipediaArticle"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#StatusOfLocation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STATUSOFLOCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STATUSOFLOCATION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#StatusOfLocation"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#StatusOfPOIs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STATUSOFPOIS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STATUSOFPOIS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#StatusOfPOIs"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasAssessment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASASSESSMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASASSESSMENT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasAssessment"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasBuildingUse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBUILDINGUSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBUILDINGUSE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasBuildingUse"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasCharacteristic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHARACTERISTIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHARACTERISTIC = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasCharacteristic"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasCityPlanningAct
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCITYPLANNINGACT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCITYPLANNINGACT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasCityPlanningAct"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasLocation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLOCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLOCATION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasLocation"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasRegion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREGION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREGION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasRegion"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTYPE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#hasType"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#participatesIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTICIPATESIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTICIPATESIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/nurulfirdaus/ontologies/2017/11/realestate#participatesIn"));

    /* ***************************************************
     * Object Property http://www.w3.org/1999/02/22-rdf-syntax-ns#type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RDF:TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RDF:TYPE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"));

    /* ***************************************************
     * Object Property http://www.w3.org/2000/01/rdf-schema#domain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RDFS:DOMAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RDFS:DOMAIN = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#domain"));

    /* ***************************************************
     * Object Property http://www.w3.org/2000/01/rdf-schema#range
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RDFS:RANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RDFS:RANGE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#range"));

    /* ***************************************************
     * Object Property http://www.w3.org/2000/01/rdf-schema#subClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RDFS:SUBCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RDFS:SUBCLASSOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#subClassOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#allValuesFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ALLVALUESFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ALLVALUESFROM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#allValuesFrom"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#assertionProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ASSERTIONPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ASSERTIONPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#assertionProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#complementOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:COMPLEMENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:COMPLEMENTOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#complementOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#datatypeComplementOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:DATATYPECOMPLEMENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:DATATYPECOMPLEMENTOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#datatypeComplementOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#disjointUnionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:DISJOINTUNIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:DISJOINTUNIONOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#disjointUnionOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#disjointWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:DISJOINTWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:DISJOINTWITH = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#disjointWith"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#distinctMembers
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:DISTINCTMEMBERS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:DISTINCTMEMBERS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#distinctMembers"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#equivalentClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:EQUIVALENTCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:EQUIVALENTCLASS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#equivalentClass"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#hasKey
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:HASKEY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:HASKEY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#hasKey"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#hasSelf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:HASSELF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:HASSELF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#hasSelf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:HASVALUE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:HASVALUE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#hasValue"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#intersectionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:INTERSECTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:INTERSECTIONOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#intersectionOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#inverseOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:INVERSEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:INVERSEOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#inverseOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#onClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONCLASS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#onClass"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#onDataRange
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONDATARANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONDATARANGE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#onDataRange"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#onDatatype
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONDATATYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONDATATYPE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#onDatatype"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#onProperties
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONPROPERTIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONPROPERTIES = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#onProperties"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#onProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#onProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#oneOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:ONEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:ONEOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#oneOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#propertyChainAxiom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:PROPERTYCHAINAXIOM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:PROPERTYCHAINAXIOM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#propertyChainAxiom"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#someValuesFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:SOMEVALUESFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:SOMEVALUESFROM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#someValuesFrom"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#sourceIndividual
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:SOURCEINDIVIDUAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:SOURCEINDIVIDUAL = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#sourceIndividual"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#subClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:SUBCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:SUBCLASSOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#subClassOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#targetIndividual
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TARGETINDIVIDUAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:TARGETINDIVIDUAL = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#targetIndividual"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#targetValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TARGETVALUE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:TARGETVALUE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#targetValue"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#unionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:UNIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:UNIONOF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#unionOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#withRestrictions
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:WITHRESTRICTIONS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:WITHRESTRICTIONS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#withRestrictions"));

    /* ***************************************************
     * Object Property http://www.w3.org/2003/01/geo/wgs84_pos#location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOCATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2003/01/geo/wgs84_pos#location"));

    /* ***************************************************
     * Object Property http://www.w3.org/2004/02/skos/core#inScheme
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SKOS:INSCHEME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SKOS:INSCHEME = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2004/02/skos/core#inScheme"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#after
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AFTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AFTER = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#after"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#before
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BEFORE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BEFORE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#before"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#dayOfWeek
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DAY_OF_WEEK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DAY_OF_WEEK = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#dayOfWeek"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasBeginning
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_BEGINNING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_BEGINNING = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasBeginning"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasDateTimeDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DATE_TIME_DESCRIPTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DATE_TIME_DESCRIPTION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasDateTimeDescription"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasDuration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DURATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DURATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasDuration"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasDurationDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DURATION_DESCRIPTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DURATION_DESCRIPTION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasDurationDescription"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasEnd
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_END.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_END = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasEnd"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasTRS
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPORAL_REFERENCE_SYSTEM_USED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPORAL_REFERENCE_SYSTEM_USED = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasTRS"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasTemporalDuration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_TEMPORAL_DURATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_TEMPORAL_DURATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasTemporalDuration"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#hasTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_TIME = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#hasTime"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#inDateTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IN_DATE_TIME_DESCRIPTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IN_DATE_TIME_DESCRIPTION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#inDateTime"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#inTemporalPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPORAL_POSITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPORAL_POSITION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#inTemporalPosition"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#inTimePosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TIME_POSITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TIME_POSITION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#inTimePosition"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#inside
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_TIME_INSTANT_INSIDE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_TIME_INSTANT_INSIDE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#inside"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalAfter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_AFTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_AFTER = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalAfter"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalBefore
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_BEFORE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_BEFORE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalBefore"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalContains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalContains"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalDisjoint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_DISJOINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_DISJOINT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalDisjoint"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalDuring
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_DURING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_DURING = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalDuring"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalEquals
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_EQUALS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_EQUALS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalEquals"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalFinishedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_FINISHED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_FINISHED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalFinishedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalFinishes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_FINISHES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_FINISHES = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalFinishes"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_IN = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalIn"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalMeets
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_MEETS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_MEETS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalMeets"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalMetBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_MET_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_MET_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalMetBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalOverlappedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_OVERLAPPED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_OVERLAPPED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalOverlappedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalOverlaps
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_OVERLAPS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_OVERLAPS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalOverlaps"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalStartedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_STARTED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_STARTED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalStartedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#intervalStarts
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERVAL_STARTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERVAL_STARTS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#intervalStarts"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#monthOfYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MONTH_OF_YEAR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MONTH_OF_YEAR = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#monthOfYear"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#timeZone
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IN_TIME_ZONE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IN_TIME_ZONE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#timeZone"));

    /* ***************************************************
     * Object Property http://www.w3.org/2006/time#unitType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPORAL_UNIT_TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPORAL_UNIT_TYPE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2006/time#unitType"));

    /* ***************************************************
     * Object Property http://xmlns.com/foaf/0.1/maker
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOAF:MAKER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOAF:MAKER = factory.getOWLObjectProperty(IRI.create("http://xmlns.com/foaf/0.1/maker"));

    /* ***************************************************
     * Data Property http://purl.org/NET/c4dm/event.owl#hasLiteralFactor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLITERALFACTOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLITERALFACTOR = factory.getOWLDataProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#hasLiteralFactor"));

    /* ***************************************************
     * Data Property http://purl.org/NET/c4dm/event.owl#literal_factor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LITERAL_FACTOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LITERAL_FACTOR = factory.getOWLDataProperty(IRI.create("http://purl.org/NET/c4dm/event.owl#literal_factor"));

    /* ***************************************************
     * Data Property http://purl.org/dc/elements/1.1/date
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DC:DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DC:DATE = factory.getOWLDataProperty(IRI.create("http://purl.org/dc/elements/1.1/date"));

    /* ***************************************************
     * Data Property http://purl.org/dc/elements/1.1/description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DC:DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DC:DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://purl.org/dc/elements/1.1/description"));

    /* ***************************************************
     * Data Property http://purl.org/dc/elements/1.1/title
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DC:TITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DC:TITLE = factory.getOWLDataProperty(IRI.create("http://purl.org/dc/elements/1.1/title"));

    /* ***************************************************
     * Data Property http://purl.org/dc/terms/identifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DCTERMS:IDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DCTERMS:IDENTIFIER = factory.getOWLDataProperty(IRI.create("http://purl.org/dc/terms/identifier"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#alternateName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GEONAMES:ALTERNATENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GEONAMES:ALTERNATENAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#alternateName"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#colloquialName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLLOQUIAL_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLLOQUIAL_NAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#colloquialName"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#countryCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISO_COUNTRY_CODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISO_COUNTRY_CODE = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#countryCode"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#geonamesID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GEONAMES_IDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GEONAMES_IDENTIFIER = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#geonamesID"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#historicalName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HISTORICAL_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HISTORICAL_NAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#historicalName"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#name"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#officialName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OFFICIAL_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OFFICIAL_NAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#officialName"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#population
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POPULATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POPULATION = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#population"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#postalCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POSTAL_CODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POSTAL_CODE = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#postalCode"));

    /* ***************************************************
     * Data Property http://www.geonames.org/ontology#shortName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SHORT_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SHORT_NAME = factory.getOWLDataProperty(IRI.create("http://www.geonames.org/ontology#shortName"));

    /* ***************************************************
     * Data Property http://www.w3.org/1999/02/22-rdf-syntax-ns#literal
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RDF:LITERAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RDF:LITERAL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/1999/02/22-rdf-syntax-ns#literal"));

    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RDFS:LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RDFS:LABEL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#label"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#cardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:CARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:CARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#cardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#maxCardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:MAXCARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:MAXCARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#maxCardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#maxQualifiedCardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:MAXQUALIFIEDCARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:MAXQUALIFIEDCARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#maxQualifiedCardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#minCardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:MINCARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:MINCARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#minCardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#minQualifiedCardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:MINQUALIFIEDCARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:MINQUALIFIEDCARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#minQualifiedCardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#qualifiedCardinality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:QUALIFIEDCARDINALITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL:QUALIFIEDCARDINALITY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#qualifiedCardinality"));

    /* ***************************************************
     * Data Property http://www.w3.org/2004/02/skos/core#altLabel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SKOS:ALTLABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SKOS:ALTLABEL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2004/02/skos/core#altLabel"));

    /* ***************************************************
     * Data Property http://www.w3.org/2004/02/skos/core#notation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NOTATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NOTATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2004/02/skos/core#notation"));

    /* ***************************************************
     * Data Property http://www.w3.org/2004/02/skos/core#prefLabel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SKOS:PREFLABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SKOS:PREFLABEL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2004/02/skos/core#prefLabel"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#day
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DAY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DAY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#day"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#dayOfYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DAY_OF_YEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DAY_OF_YEAR = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#dayOfYear"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#days
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DAYS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DAYS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#days"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#hasXSDDuration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_XSD_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_XSD_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#hasXSDDuration"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#hour
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HOUR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HOUR = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#hour"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#hours
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HOURS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HOURS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#hours"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#inXSDDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IN_XSD_DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IN_XSD_DATE = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#inXSDDate"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#inXSDDateTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IN_XSD_DATE_TIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IN_XSD_DATE_TIME = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#inXSDDateTime"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#inXSDDateTimeStamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IN_XSD_DATE_TIME_STAMP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IN_XSD_DATE_TIME_STAMP = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#inXSDDateTimeStamp"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#inXSDgYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IN_XSD_G_YEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IN_XSD_G_YEAR = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#inXSDgYear"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#inXSDgYearMonth
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IN_XSD_G_YEARMONTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IN_XSD_G_YEARMONTH = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#inXSDgYearMonth"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#minute
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MINUTE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MINUTE = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#minute"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#minutes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MINUTES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MINUTES = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#minutes"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#month
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MONTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MONTH = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#month"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#months
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MONTHS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MONTHS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#months"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#nominalPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME_OF_TEMPORAL_POSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME_OF_TEMPORAL_POSITION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#nominalPosition"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#numericDuration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NUMERIC_VALUE_OF_TEMPORAL_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NUMERIC_VALUE_OF_TEMPORAL_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#numericDuration"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#numericPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NUMERIC_VALUE_OF_TEMPORAL_POSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NUMERIC_VALUE_OF_TEMPORAL_POSITION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#numericPosition"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#second
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SECOND.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SECOND = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#second"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#seconds
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SECONDS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SECONDS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#seconds"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#week
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WEEK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WEEK = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#week"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#weeks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WEEKS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WEEKS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#weeks"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#xsdDateTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_XSD_DATE_TIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_XSD_DATE_TIME = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#xsdDateTime"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#year
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property YEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_YEAR = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#year"));

    /* ***************************************************
     * Data Property http://www.w3.org/2006/time#years
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property YEARS_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_YEARS_DURATION = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2006/time#years"));

    /* ***************************************************
     * Data Property http://xmlns.com/foaf/0.1/name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FOAF:NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FOAF:NAME = factory.getOWLDataProperty(IRI.create("http://xmlns.com/foaf/0.1/name"));


}
